Fix: libcrmcommon: use uint32_t integers for 32-bit magic numbers
So that they are correctly handled on 32-bit systems.

Previously unit test would fail on 32-bit systems:

  > lib/common/tests/xml/crm_xml_init_test
  TAP version 13
  1..8
  ok 1 - buffer_scheme_test
  not ok 2 - create_document_node
  # 0xffffffff81726354 != 0x81726354
  # crm_xml_init_test.c:61: error: Failure!