Fix: libcrmcommon: prevent external callers from triggering assertion when connecting to cluster
When sbd is connecting to cluster by calling crm_cluster_connect() ->
pcmk_cluster_connect() -> pcmk__corosync_connect() ->
pcmk__cpg_connect() -> pcmk__server_message_type()

, it triggers assertion:

error: log_assertion_as: pcmk__server_message_type: Triggered fatal
assertion at servers.c:165 : (server > 0) && (server <
PCMK__NELEM(server_info))

This fixes it by avoiding calling pcmk__server_message_type() in
pcmk__cpg_connect().

I don't see sbd invoke pcmk__cpg_message_data() ->
check_message_sanity() -> msg_type2text(). But since msg_type2text() is
only used for informative logging, prevent it from triggering assertion
anyway.